
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-6pm-2
owner: ucsb-cs156-f23
repo_name: team01-f23-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjI2Njk2NTky","is_bot":false,"login":"SparklyJeff","name":"Jeffrey Cao"},"headRefName":"Jeffrey-Joke","number":19,"title":"Joke Service is created ","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-2/pull/19"},{"author":{"id":"MDQ6VXNlcjU5Mzc5NDY0","is_bot":false,"login":"justinchung712","name":""},"headRefName":"Justin-PublicHoliday","number":18,"title":"Add PublicHoliday Service","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-2/pull/18"}]
