
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-6pm-2
owner: ucsb-cs156-f23
repo_name: team01-f23-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjY4NzUyNjY1","is_bot":false,"login":"ZhenyuYu1","name":"Zhenyu Yu"},"headRefName":"Zhenyu-READMEFixes","number":32,"title":"added title, table, repo, dokku link","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-2/pull/32"},{"author":{"id":"MDQ6VXNlcjg2NDkxMjg5","is_bot":false,"login":"cstraw2021","name":""},"headRefName":"Chris-Location-Controller","number":31,"title":"Implemented Location Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-2/pull/31"},{"author":{"id":"MDQ6VXNlcjg2NDkxMjg5","is_bot":false,"login":"cstraw2021","name":""},"headRefName":"Chris-Location","number":30,"title":"Location Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-2/pull/30"}]
