
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-6pm-2
owner: ucsb-cs156-f23
repo_name: team01-f23-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyODM5MjIz","is_bot":false,"login":"whuang602","name":"Will H."},"headRefName":"William-Tides-Controller","number":25,"title":"Add Tides Controller and Test","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-2/pull/25"},{"author":{"id":"MDQ6VXNlcjcyODM5MjIz","is_bot":false,"login":"whuang602","name":"Will H."},"headRefName":"William-Tides","number":23,"title":"Add Tides Service and Test","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-2/pull/23"},{"author":{"id":"MDQ6VXNlcjY4NzUyNjY1","is_bot":false,"login":"ZhenyuYu1","name":"Zhenyu Yu"},"headRefName":"Zhenyu-Zipcode-Controller","number":22,"title":"Add ZipCode Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-2/pull/22"},{"author":{"id":"MDQ6VXNlcjU5Mzc5NDY0","is_bot":false,"login":"justinchung712","name":""},"headRefName":"Justin-PublicHoliday-Controller","number":21,"title":"Add PublicHoliday Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-2/pull/21"}]
